### ISSUE TITLE
Not started

### ISSUE THREAD

**Issue by OleksandrGonchar** [igniteram/appium-webdriverio-typescript#13]
I can't start this project - failed on start
I installed all dependencies and start appium server, virtual device and change virtual device name and android version into wdio.app.config but start application tests return an error

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'app-test' ]
2 info using npm@6.1.0
3 info using node@v10.3.0
4 verbose run-script [ 'preapp-test', 'app-test', 'postapp-test' ]
5 info lifecycle appium-webdriverio-tests@1.0.0~preapp-test: appium-webdriverio-tests@1.0.0
6 info lifecycle appium-webdriverio-tests@1.0.0~app-test: appium-webdriverio-tests@1.0.0
7 verbose lifecycle appium-webdriverio-tests@1.0.0~app-test: unsafe-perm in lifecycle true
8 verbose lifecycle appium-webdriverio-tests@1.0.0~app-test: PATH: C:\Users\Oleksandr\AppData\Roaming\nvm\v10.3.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\hobby\test\appium-webdriverio-typescript\node_modules\.bin;C:\Users\Oleksandr\AppData\Roaming\nvm\v10.3.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\hobby\test\appium-webdriverio-typescript\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\Oleksandr\AppData\Local\Android\sdk\tools;C:\Users\Oleksandr\AppData\Local\Android\sdk\tools\bin;C:\Users\Oleksandr\AppData\Local\Android\sdk\build-tools;C:\Users\Oleksandr\AppData\Local\Android\sdk\platform-tools;C:\Users\Oleksandr\AppData\Local\Android\sdk\emulator;C:\WINDOWS\System32\OpenSSH\;C:\Users\Oleksandr\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Android\Android Studio 2;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Users\Oleksandr\AppData\Local\atom\bin;C:\Users\Oleksandr\AppData\Local\Microsoft\WindowsApps;C:\ant\bin;C:\Program Files\Microsoft VS Code\bin;C:\Python27;C:\Users\Oleksandr\AppData\Local\Android\sdk\tools;C:\Users\Oleksandr\AppData\Local\Android\sdk\tools\bin;C:\Users\Oleksandr\AppData\Local\Android\sdk\build-tools;C:\Users\Oleksandr\AppData\Local\Android\sdk\platform-tools;C:\Users\Oleksandr\AppData\Local\Android\sdk\emulator;C:\Users\Oleksandr\AppData\Local\Android\sdk;C:\Users\Oleksandr\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle appium-webdriverio-tests@1.0.0~app-test: CWD: D:\hobby\test\appium-webdriverio-typescript
10 silly lifecycle appium-webdriverio-tests@1.0.0~app-test: Args: [ '/d /s /c', 'wdio ./config/wdio.app.config.js' ]
11 silly lifecycle appium-webdriverio-tests@1.0.0~app-test: Returned: code: 1  signal: null
12 info lifecycle appium-webdriverio-tests@1.0.0~app-test: Failed to exec app-test script
13 verbose stack Error: appium-webdriverio-tests@1.0.0 app-test: `wdio ./config/wdio.app.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Oleksandr\AppData\Roaming\nvm\v10.3.0\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Oleksandr\AppData\Roaming\nvm\v10.3.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid appium-webdriverio-tests@1.0.0
15 verbose cwd D:\hobby\test\appium-webdriverio-typescript
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "app-test"
18 verbose node v10.3.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error appium-webdriverio-tests@1.0.0 app-test: `wdio ./config/wdio.app.config.js`
22 error Exit status 1
23 error Failed at the appium-webdriverio-tests@1.0.0 app-test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by igniteram** [comment]
@OleksandrGonchar Were you able to solve this issue, looks like config issue. Let me know is it still exists if not I could close this issue.

**Comment by anemadagu11978** [comment]
I am also getting a similar error . All my tests are failing!

88e9fe626cea:~$ npm run app-test

> appium-webdriverio-tests@1.0.0 app-test /Users/appiumtypescriptwebdriverio/appium-webdriverio-typescript
> wdio ./config/wdio.app.config.js

<<< NATIVE APP TESTS STARTED >>>


0 passing (82.40s)

<<< TESTING FINISHED >>>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-webdriverio-tests@1.0.0 app-test: `wdio ./config/wdio.app.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-webdriverio-tests@1.0.0 app-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2019-07-29T19_09_29_017Z-debug.log
88e9fe626cea:~$
@88e9fe626cea:~$ npm run browser-test

> appium-webdriverio-tests@1.0.0 browser-test /Users/appiumtypescriptwebdriverio/appium-webdriverio-typescript
> wdio ./config/wdio.browser.config.js

<<< BROWSER TESTS STARTED >>>


0 passing (82.40s)

<<< TESTING FINISHED >>>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-webdriverio-tests@1.0.0 browser-test: `wdio ./config/wdio.browser.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-webdriverio-tests@1.0.0 browser-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2019-07-29T19_11_37_726Z-debug.log
88e9fe626cea:~$
here is the config file
/**
 * WebdriverIO config file to run tests on native mobile apps.
 * Config file helps us configure all the settings and setup environments 
 * to run our tests.
 */

const host = '127.0.0.1';   // default appium host
const port = 4730;          // default appium port

const waitforTimeout = 30 * 60000;
const commandTimeout = 30 * 60000;

exports.config = {
    debug: false,
    specs: [
        './features/calculator.feature',
    ],

    reporters: ['allure','spec'],
    reporterOptions: {
        allure: {
            outputDir: './allure-results/'
        }
    },

    host: host,
    port: port,

    maxInstances: 1,

    capabilities: [
        {
            appiumVersion: '1.8.1',                 // Appium module version
            browserName: '',                        // browser name is empty for native apps
            platformName: 'Android',
            app: './app/LGCalculator.apk',          // Path to your native app
            appPackage: 'com.android.calculator2',  // Package name of your app
            appActivity: 'com.android.calculator2.Calculator', // App activity of the app
            platformVersion: '7.1.1',              // Android platform version of the device
            deviceName: 'emulator-5554', //THF755e0384',              // device name of the mobile device
            waitforTimeout: waitforTimeout,
            commandTimeout: commandTimeout,
            newCommandTimeout: 30 * 60000,
        }
    ],

    services: ['appium'],
    appium: {
        waitStartTime: 6000,
        waitforTimeout: waitforTimeout,
        command: 'appium',
        logFileName: 'appium.log',
        args: {
            address: host,
            port: port,
            commandTimeout: commandTimeout,
            sessionOverride: true,
            debugLogSpacing: true
        }
    },

    /**
     * test configurations
     */
    logLevel: 'silent',
    coloredLogs: true,
    framework: 'cucumber',          // cucumber framework specified 
    cucumberOpts: {
        compiler: ['ts:ts-node/register'],
        backtrace: true,
        failFast: false,
        timeout: 5 * 60 * 60000,
        require: ['./stepDefinitions/calcSteps.ts']      // importing/requiring step definition files
    },

    /**
     * hooks help us execute the repeatitive and common utilities 
     * of the project.
     */
    onPrepare: function () {
        console.log('<<< NATIVE APP TESTS STARTED >>>');
    },

    afterScenario: function (scenario) {
        browser.screenshot();
     },

    onComplete: function () {
        console.log('<<< TESTING FINISHED >>>');
    }

};
